[package]
name = "meteroid-store"
version = "0.1.0"
license.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common-eventbus.workspace = true

argon2 = { workspace = true, features = ["rand"] }
base62.workspace = true
backon = { workspace = true }
cached = { workspace = true, features = ["async", "tokio"] }
chrono = { workspace = true, features = ["clock", "serde"] }
diesel.workspace = true
diesel-async.workspace = true
uuid = { workspace = true, features = ["serde"] }
nanoid.workspace = true
tracing.workspace = true
tracing-log = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
serde_with = { workspace = true }
o2o.workspace = true
error-stack.workspace = true
thiserror.workspace = true
diesel-models.workspace = true
async-trait.workspace = true
rand.workspace = true
rust_decimal.workspace = true
rust_decimal_macros.workspace = true
rusty-money = { workspace = true }
common-utils = { workspace = true }
itertools.workspace = true
secrecy = { workspace = true, features = ["serde"] }
svix = { workspace = true, features = ["http2", "rustls-tls"] }
governor = { workspace = true }
nonzero_ext = { workspace = true }
chacha20poly1305 = { workspace = true }
hex = { workspace = true }
url = { workspace = true }
jsonwebtoken = { workspace = true, features = ["aws_lc_rs"] }
futures = { workspace = true }
once_cell = { workspace = true }
rustls = { workspace = true, features = ["ring"] }
rust_iso3166 =  { workspace = true }
tokio-postgres-rustls = { workspace = true }
tokio = { workspace = true, default-features = false, features = ["macros", "rt-multi-thread"] }
tokio-postgres = { workspace = true }
strum = { workspace = true, features = ["derive", "std"] }
meteroid-mailer = { workspace = true }
meteroid-oauth = { workspace = true }
stripe-client = { workspace = true }
common-domain = { workspace = true }
metering-grpc = { workspace = true }
prost-types = { workspace = true }
log.workspace = true
golden.workspace = true
paste.workspace = true
meteroid-store-macros = { workspace = true }
meteroid-tax = { workspace = true }
ctor = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }

[features]
test-utils = []
